using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using Microsoft.CodeAnalysis;
using RepositoryPatternGenerator.Helpers;

namespace RepositoryPatternGenerator.CodeSnippets
{
    public class CodeSnippetsV2
    {
        private const string Header = @"/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/
";
        public static string RepositoryName = "Repository";
        public static string ModelsName = "Models";
        public static string ViewModelsProjectName = "DataModel";
        public static string MainProjectName = "MainProject";

        public static string GetModelRepository(string modelName)
        {
            return @"" + Header + @"
using System.Data.Entity;
using " + RepositoryName + @".Adapter;
using " + RepositoryName + @".Model;
using " + RepositoryName + @".Repository;
using " + ViewModelsProjectName + @".ViewModel;

namespace " + MainProjectName + @".Repository
{
    public class " + modelName + @"Repository : EntityFrameworkRepository<" + modelName + @", " + modelName + @"Model, " + modelName + @"Adapter>
    {
        public " + modelName + @"Repository(DbContext context) : base(context) { }
    }
}
";
        }


        public static string GetViewModel(string modelName, Dictionary<string, string> modelProps)
        {
            var props = modelProps.Aggregate("", (current, mp) => current + $"        public {mp.Value} {mp.Key} {{ get; set; }}\r\n");
            props = Utils.ReplaceLastOccurrence(props, "\r\n", "");

            var code = @"" + Header + @"
using System;

namespace " + ViewModelsProjectName + @".ViewModel
{
    public class " + modelName + @"Model
    {
" + props + @"
    }
}
";
            return code;
        }

        public static string GetModelAdapter(string modelName, List<string> modelProps)
        {
            var fromProps = modelProps.Aggregate("", (current, mp) => current + $"                {mp} = model.{mp},\r\n");
            fromProps = Utils.ReplaceLastOccurrence(fromProps, ",\r\n", "");

            var code = @"" + Header + @"
using " + RepositoryName + @".Model;
using " + ViewModelsProjectName + @".ViewModel;

namespace " + RepositoryName + @".Adapter
{
    public class " + modelName + @"Adapter : Adapter<" + modelName + @", " + modelName + @"Model>
    {
        public override " + modelName + @" FromViewModel(" + modelName + @"Model model)
        {
            return new " + modelName + @"()
            {
" + fromProps + @"
            };
        }

        public override " + modelName + @"Model FromModel(" + modelName + @" model)
        {
            return new " + modelName + @"Model()
            {
" + fromProps + @"
            };
        }
    }
}
";
            return code;
        }

        public static string GetIAdapter()
        {
            return @"" + Header + @"
using System.Collections.Generic;

namespace " + RepositoryName + @".Adapter
{
    public interface IAdapter<TEntity, TModel>
    {
        TEntity FromViewModel(TModel model);
        TModel FromModel(TEntity model);
        ICollection<TEntity> FromViewModel(ICollection<TModel> model);
        ICollection<TModel> FromModel(ICollection<TEntity> model);
    }
}";
        }
        public static string GetAdapter()
        {
            return @"" + Header + @"
using System.Collections.Generic;
using System.Linq;

namespace " + RepositoryName + @".Adapter
{
    public abstract class Adapter<TEntity, TModel> : IAdapter<TEntity, TModel>
    {
        public abstract TEntity FromViewModel(TModel model);
        public abstract TModel FromModel(TEntity model);

        public ICollection<TEntity> FromViewModel(ICollection<TModel> model)
        {
            return model.Select(FromViewModel).ToList();
        }

        public ICollection<TModel> FromModel(ICollection<TEntity> model)
        {
            return model.Select(FromModel).ToList();
        }
    }
}";
        }

        public static string GetIRepository()
        {
            return @"" + Header + @"
using System;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace " + RepositoryName + @".Repository
{
    public interface IRepository<TEntity, TModel, TAdapter>
    {
        ICollection<TModel> Get();
        TModel Get(params object[] keys);
        ICollection<TModel> Get(Expression<Func<TEntity, bool>> where);
        TModel Add(TModel model);
        int Update(TModel model);
        int Delete(params object[] keys);
        int Delete(TModel model);
        int Delete(Expression<Func<TEntity, bool>> where);
    }
}";
        }

        public static string GetEntityFrameworkRepository()
        {
            return @"" + Header + @"
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using " + RepositoryName + @".Adapter;

namespace " + RepositoryName + @".Repository
{
    public class EntityFrameworkRepository<TEntity, TModel, TAdapter> : IRepository<TEntity, TModel, TAdapter>
        where TAdapter : IAdapter<TEntity, TModel>, new()
        where TEntity : class
        where TModel : class
    {
        protected DbContext Context;

        protected DbSet<TEntity> DbSet => Context.Set<TEntity>();

        public TAdapter Adapter
        {
            get
            {
                if (_adapter == null)
                    _adapter = new TAdapter();
                return _adapter;
            }
        }
        private TAdapter _adapter;

        public EntityFrameworkRepository(DbContext context)
        {
            Context = context;
        }

        public virtual ICollection<TModel> Get()
        {
            return Adapter.FromModel(DbSet.ToList());
        }

        public virtual TModel Get(params object[] keys)
        {
            var data = DbSet.Find(keys);
            return Adapter.FromModel(data);
        }

        public virtual ICollection<TModel> Get(Expression<Func<TEntity, bool>> where)
        {
            var data = DbSet.Where(where);
            return Adapter.FromModel(data.ToList());
        }

        public virtual TModel Add(TModel model)
        {
            var data = Adapter.FromViewModel(model);
            DbSet.Add(data);
            try
            {
                Context.SaveChanges();
                return Adapter.FromModel(data);
            }
            catch (Exception)
            {
                return null;
            }
        }

        public virtual int Update(TModel model)
        {
            var data = Adapter.FromViewModel(model);
            Context.Entry(data).State = EntityState.Modified;
            try
            {
                return Context.SaveChanges();
            }
            catch (Exception)
            {
                return -1;
            }
        }

        public virtual int Delete(params object[] keys)
        {
            var data = DbSet.Find(keys);
            DbSet.Remove(data);
            try
            {
                return Context.SaveChanges();
            }
            catch (Exception)
            {
                return -1;
            }
        }

        public virtual int Delete(TModel model)
        {
            var data = Adapter.FromViewModel(model);
            Context.Entry(data).State = EntityState.Deleted;
            try
            {
                return Context.SaveChanges();
            }
            catch (Exception)
            {
                return -1;
            }
        }

        public virtual int Delete(Expression<Func<TEntity, bool>> where)
        {
            var data = DbSet.Where(where);
            DbSet.RemoveRange(data);
            try
            {
                return Context.SaveChanges();
            }
            catch (Exception)
            {
                return -1;
            }
        }
    }
}";
        }
    }
}