using System.Collections.Generic;
using System.Linq;

namespace RepositoryPatternGenerator.CodeSnippets
{
    public class CodeSnippets
    {
        private const string Header = @"/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/
";
        public static string RepositoryName = "Repository";
        public static string ModelsName = "Models";

        public static string GenerateClassViewModel(string className, Dictionary<string, string> properties,
            List<string> keys)
        {
            var propsString = "";
            var toModelString = "";
            var fromModelString = "";
            var updateModelString = "";
            var keysString = "";

            foreach (var p in properties.Select((Entry, Index) => new { Entry, Index }))
            {
                propsString += "        public " + p.Entry.Value + " " + p.Entry.Key + " { get; set; }";
                fromModelString += "            " + p.Entry.Key + " = model." + p.Entry.Key + ";";
                updateModelString += "            model." + p.Entry.Key + " = " + p.Entry.Key + ";";
                toModelString += "                " + p.Entry.Key + " = " + p.Entry.Key;
                if (p.Index + 1 < properties.Count)
                {
                    propsString += "\r\n";
                    toModelString += ",\r\n";
                    fromModelString += "\r\n";
                    updateModelString += "\r\n";
                }
            }

            foreach (var k in keys.Select((Entry, Index) => new { Entry, Index }))
            {
                keysString += k.Entry;
                if (k.Index + 1 < keys.Count)
                    keysString += ",";
            }

            var classViewModel =
                @"" + Header + @"
using " + RepositoryName + "." + ModelsName + @";
using System;

namespace " + RepositoryName + @".ViewModels
{
    public class " + className + @"ViewModel : IViewModel<" + className + @">
    {
" + propsString + @"

        public " + className + @" ToModel()
        {
            return new " + className + @"()
            {
" + toModelString + @"
            };
        }

        public void FromModel(" + className + @" model)
        {
" + fromModelString + @"
        }

        public void UpdateModel(" + className + @" model)
        {
" + updateModelString + @"
        }

        public object[] GetKeys()
        {
            return new object[] { " + keysString + @" };
        }
    }
}";

            return classViewModel;
        }

        public static string GetIRepository()
        {
            return @"" + Header + @"
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using " + RepositoryName + @".ViewModels;

namespace " + RepositoryName + @".Repository
{
    public interface IRepository<TModel, TViewModel> where TModel : class where TViewModel : IViewModel<TModel>
    {
        ICollection<TViewModel> Get();
        TViewModel Get(params object[] keys);
        ICollection<TViewModel> Get(Expression<Func<TModel, bool>> where, Expression<Func<TModel, object>> orderBy = null, bool? orderAsc = null, int? skip = null, int? take = null);
        int Count(Expression<Func<TModel, bool>> where = null);        
        TViewModel Add(TViewModel model);
        int Update(TViewModel model);
        int Delete(params object[] keys);
        int Delete(Expression<Func<TModel, bool>> where);
    }
}";
        }

        public static string GetIViewModel()
        {
            return @"" + Header + @"
namespace " + RepositoryName + @".ViewModels
{
    public interface IViewModel<TModel> where TModel : class
        {
            TModel ToModel();
            void FromModel(TModel model);
            void UpdateModel(TModel model);
            object[] GetKeys();
        }
}";
        }

        public static string GetEntityRepository()
        {
            return @"" + Header + @"
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using " + RepositoryName + @".ViewModels;
using " + RepositoryName + @".Helpers;
using System.Reflection;
using System.Collections.ObjectModel;

namespace " + RepositoryName + @".Repository
{
    public class EntityRepository<TModel, TViewModel> : IRepository<TModel, TViewModel> where TModel : class where TViewModel : IViewModel<TModel>, new()
    {
        private readonly DbContext _context;

        protected virtual DbSet<TModel> DbSet
        {
            get
            {
                return _context.Set<TModel>();
            }
        }

        public EntityRepository(DbContext context)
        {
            this._context = context;
        }

        public virtual ICollection<TViewModel> Get()
        {
            var list = new List<TViewModel>();
            foreach (var model in DbSet)
            {
                var vm = new TViewModel();
                vm.FromModel(model);
                list.Add(vm);
            }

            return list;
        }

        public virtual TViewModel Get(params object[] keys)
        {
            var data = DbSet.Find(keys);
            if (data == null)
                return default(TViewModel);

            var vm = new TViewModel();
            vm.FromModel(data);

            return vm;
        }

        public Expression<Func<TModel, TNewKey>> Convert<TNewKey>(MemberExpression expression, ReadOnlyCollection<ParameterExpression> parameterExpressions)
        {
            return Expression.Lambda<Func<TModel, TNewKey>>(expression, parameterExpressions);
        }

        public IQueryable<TModel> GetSpecific<TOrderBy>(Expression<Func<TModel, bool>> where, int? skip, int? take, Expression<Func<TModel, TOrderBy>> orderBy = null, bool? orderAsc = null)
        {
            var query = DbSet.Where(where);

            if (orderBy == null)
                return query;

            if (orderAsc == null)
                query = query.OrderBy(orderBy);
            else if (orderAsc.Value)
                query = query.OrderBy(orderBy);
            else
                query = query.OrderByDescending(orderBy);

            if (skip != null)
                query = query.Skip(skip.Value);

            if (take != null)
                query = query.Take(take.Value);

            return query;
        }

        public virtual ICollection<TViewModel> Get(Expression<Func<TModel, bool>> where, Expression<Func<TModel, object>> orderBy = null, bool? orderAsc = null, int? skip = null, int? take = null)
        {
            IQueryable<TModel> queryData;

            if (orderBy != null)
            {
                var propertyAccessExpression = new ExpressionHelper().GetPropertyAccessExpression(orderBy);
                var propertyInfo = (PropertyInfo)propertyAccessExpression.Member;

                var covertMethod = GetType().GetMethod(""Convert"").MakeGenericMethod(propertyInfo.PropertyType);
                var getOrderedMethod = GetType().GetMethod(""GetSpecific"").MakeGenericMethod(propertyInfo.PropertyType);

                var newExpression = covertMethod.Invoke(this, new object[] { propertyAccessExpression, orderBy.Parameters });
                queryData = (IQueryable<TModel>)getOrderedMethod.Invoke(this, new[] { where, skip, take, newExpression, orderAsc });
            }
            else
                queryData = GetSpecific<object>(where, null, null);

            var data = new List<TViewModel>();

            foreach (var model in queryData)
            {
                var obj = new TViewModel();
                obj.FromModel(model);
                data.Add(obj);
            }

            return data;
        }

        public virtual int Count(Expression<Func<TModel, bool>> where = null)
        {
            return where != null ? DbSet.Where(where).Count() : DbSet.Count();
        }

        public virtual TViewModel Add(TViewModel model)
        {
            var m = model.ToModel();
            var addedModel = DbSet.Add(m);
            try
            {
                _context.SaveChanges();
                model.FromModel(addedModel);
                return model;
            }
            catch (Exception)
            {
                return default(TViewModel);
            }
        }

        public virtual int Update(TViewModel model)
        {
            var obj = DbSet.Find(model.GetKeys());
            model.UpdateModel(obj);
            try
            {
                return _context.SaveChanges();
            }
            catch (Exception)
            {
                return 0;
            }
        }

        public virtual int Delete(Expression<Func<TModel, bool>> where)
        {
            var data = DbSet.Where(where);
            DbSet.RemoveRange(data);
            try
            {
                return _context.SaveChanges();
            }
            catch (Exception)
            {
                return 0;
            }
        }

        public virtual int Delete(params object[] keys)
        {
            var data = DbSet.Find(keys);
            DbSet.Remove(data);
            try
            {
                return _context.SaveChanges();
            }
            catch (Exception)
            {
                return 0;
            }
        }
    }
}";
        }

        public static string GetExpressionHelper()
        {
            var code = @"" + Header + @"
using System.Linq.Expressions;
using System.Reflection;

namespace Repository.Helpers
{
    public class ExpressionHelper : ExpressionVisitor
    {
        private MemberExpression _memberExpression;

        public MemberExpression GetPropertyAccessExpression(Expression expression)
        {
            _memberExpression = null;

            Visit(expression);

            return _memberExpression;
        }

        protected override Expression VisitMember(MemberExpression node)
        {
            var property = node.Member as PropertyInfo;

            if (property != null)
                _memberExpression = node;

            return base.VisitMember(node);
        }
    }
}";
            return code;
        }
    }
}
